catalog/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.catalog, name='catalog'),
    re_path(r'^books/$', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
]

homelibrary/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
#from django.views.generic import RedirectView
from catalog import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('catalog/', include('catalog.urls')),
    #path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

catalog/models.py
# Model field reference  https://docs.djangoproject.com/en/4.2/ref/models/fields/
# Model Meta options https://docs.djangoproject.com/en/4.2/ref/models/options/#model-meta-options
# QuerySet API reference https://docs.djangoproject.com/en/4.2/ref/models/querysets/
# Field lookups https://docs.djangoproject.com/en/4.2/ref/models/querysets/#field-lookups

from django.db import models
from django.urls import reverse
import uuid

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text="Append to genre")
    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=200, help_text="Append to Title")
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN',max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])
    
    def display_genre(self):
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
    display_genre.short_description = 'Genre'

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

    class Meta:
        ordering = ["due_back"]


    def __str__(self):

        return '%s (%s)' % (self.id,self.book.title)

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)

class User(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    full_name = models.CharField(max_length=128, blank=True)
    email_addr = models.EmailField(max_length=128, blank=True)
    telephone_number = models.CharField(max_length=32)

    def get_absolute_url(self):
        return reverse('user-detail', args=[str(self.id)])

    def __str__(self):
        return '%s, %s' % (self.first_name, self.last_name)

catalog/views.py
#from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User, Book, Author, BookInstance, Genre

@login_required
def index(request):
    return render(request, 'index.html', context={})

class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    paginate_by = 2

class BookDetailView(generic.DetailView):
    model = Book
    
class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 2

class AuthorDetailView(generic.DetailView):
    model = Author

def catalog(request):
    num_books=Book.objects.all().count()
    num_instances=BookInstance.objects.all().count()
    num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    num_authors=Author.objects.count()  # Auto 'all()' default
    num_users=User.objects.count()

    # Number of visits to this view, as counted in the session variable.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    return render(
        request,
        'catalog.html',
        context={
            'num_books':num_books,
            'num_instances':num_instances,
            'num_instances_available':num_instances_available,
            'num_authors':num_authors,
            'num_users':num_users,
            'num_visits':num_visits # num_visits appended
            },
    )

catalog/templates/base_generic.html
<!doctype html>
<html lang="en">
  <head>
    {% block title %}<title>Library</title>{% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Добавление дополнительного статического CSS файла -->
    {% load static %}
    <link rel="icon" href="{% static 'img/favicon.ico' %}" >
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />            
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav">
              <li><a href="{% url 'catalog' %}">Home</a></li>
              <li><a href="{% url 'books' %}">All books</a></li>
              <li><a href="">All authors</a></li>
              <li><a href="">All users</a></li>
            </ul>
          {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
      </div>
    </div>
  </body>
</html>

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Book List</h1>

      <p>There are no books in the library.</p>

{% endblock %}

templates/base_generic.html
<!doctype html>
<html lang="en">
  <head>
    {% block title %}<title>Library</title>{% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Добавление дополнительного статического CSS файла -->
    {% load static %}
    <link rel="icon" href="{% static 'catalog/img/favicon.ico' %}" >
    <link rel="stylesheet" href="{% static 'catalog/css/styles.css' %}" />            
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav">
              <li><a href="{% url 'index' %}">Home</a></li>
              <li><a href="{% url 'catalog' %}">All catalog</a></li>
              <li><a href="{% url 'books' %}">All books</a></li>
              <li><a href="{% url 'authors' %}">All authors</a></li>
              <li><a href="">All users</a></li>
              

              {% if user.is_authenticated %}
                <li>User: {{ user.get_username }}</li>
                <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
              {% else %}
                <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
              {% endif %}
            </ul>
          {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
          <div>{% block pagination %}
                  {% if is_paginated %}
                    <div class="pagination">
                      <span class="page-links">
                        {% if page_obj.has_previous %}
                          <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                          <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                      </span>
                    </div>
                  {% endif %}
          </div>{% endblock %}
      </div>
    </div>
  </body>
</html>

templates/catalog.html
{% extends "base_generic.html" %}

{% block title %}<title>Catalog</title>{% endblock %}

{% block content %}
<h1>Home Library</h1>

  <p>Welcome to HomeLibrary, a very basic Django website.</p>

<h2>Dynamic content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Users:</strong> {{ num_users }}</li>
  </ul>

  <p>
    You have visited this page {{ num_visits }}
        {% if num_visits == 1 %}
            time
        {% else %}
            times
        {% endif %}.
  </p>
  
{% endblock %}

templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block title %}<title>Author Detail</title>{% endblock %}

{% block content %}

<h1>Author: {{ author }} </h1>
<p>{{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Books</h4>

<dl>
{% for book in author.book_set.all %}
  <dt><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</dt>
  <dd>{{book.summary}}</dd>
  {% empty %}
  <p>This author has no books.</p>
{% endfor %}
</dl>
</div>

{% endblock %}

templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Author List</h1>

{% if author_list %}
  <ul>

  {% for author in author_list %}
    <li>
      <a href="{{ author.get_absolute_url }}">
      {{ author }} ({{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %})
      </a>
    </li>
  {% endfor %}

 </ul>
{% else %}
  <p>There are no authors available.</p>
{% endif %}
        
{% endblock %}

templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block title %}<title>Book Detail</title>{% endblock %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block title %}<title>Book List</title>{% endblock %}

{% block content %}
    <h1>Book List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Sencha | Ext JS 7.0</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" >
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=10, user-scalable=yes">
        {% load static %}
        <link rel="icon" href="{% static 'library/resources/img/favicon.png' %}" type="image/png">
        <link rel="stylesheet" type="text/css" href="{% static 'ext/classic/theme-crisp/resources/theme-crisp-all-debug.css' %}" />
        <script type="text/javascript" src="{% static 'ext/ext-all-debug.js' %}"></script>
        <script>
            Ext.onReady(function(){
                Ext.create('Ext.container.Viewport', {
                    layout: 'border',
                    items: [{
                        region: 'north',
                        html: '<h1 class="x-panel-header">Home Library</h1>',
                        border: false,
                        margin: '0 0 5 0',
                    },{
                        region: 'west',
                        title: 'West Panel',
                        border: false,
                        width: 150
                    },{
                        region: 'center',
                        html: '<h2>Dynamic content</h2>',
                        xtype: 'tabpanel',
                        activeTab: 0,
                        items: [{
                            title: 'file',
                        },{
                            title: 'edit',
                        },{
                            title: 'help',
                        }]
                    },{
                        region: 'east',
                        title: 'East Panel',
                        collapsible: true,
                        split: false,
                        width: 300
                    },{
                        region: 'south',
                        title: 'South Panel',
                        collapsible: true,
                        html: '<div class="wrap">&copy;2024-<span id="this-year"></span> Danilov Andrey. All rights reserved.</div>',
                        split: true,
                        height: 100,
                        minHeight: 100
                    },]
                });
            });
        </script>
    </head>
    <body>
    </body>
</html>